batch_size: 32
train:
  train_size : 0.8
  epochs: 300
  learning_rate: 0.01
  momentum: 0.9
  weight_decay: 0.001
  optimizer: adam
  scheduler:
    type: step_lr
    step_size: 30
    gamma: 0.1
  criterion: mixed
  loss_method: heatmap
  accuracy: PCK
transforms:
  resizing:
    spatial_size: [512, 160]
    interpolation: bilinear
model:
  spatial_dims: 2
  in_channels: 1
  out_channels: 68
  channels: [32, 64, 128]
  strides: [2, 2]
  kernel_size: 3
  dropout: 0.3
