batch_size: 32
train:
  train_size : 0.8
  epochs: 100
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.0001
  optimizer: adam
  criterion: MSE
  loss_method: heatmap
  accuracy: euclidean
transforms:
  resizing:
    spatial_size: [1024, 512]
    interpolation: bilinear
model:
  spatial_dims: 2
  in_channels: 1
  out_channels: 68
  channels: [32, 64, 128, 256]
  strides: [2, 2, 2]
  kernel_size: 3
