batch_size: 32
train:
  epochs: 100
  train_size: 0.5
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.0001
  optimizer: adam
  scheduler:
    type: step_lr
    step_size: 30
    gamma: 0.1
  criterion: MSE
  loss_method: heatmap
  accuracy: PCK
transforms:
  resizing:
    spatial_size: [512, 160]
    interpolation: bilinear
model:
  spatial_dims: 2
  in_channels: 1
  out_channels: 68
  channels: [32, 64, 128, 256]
  strides: [2, 2, 2]
  kernel_size: 3
