batch_size: 1
train:
  train_size : 0.5
  epochs: 100
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.0001
  optimizer: adam
  scheduler:
    type: step_lr
    step_size: 30
    gamma: 0.1
  criterion: MSE
  loss_method: heatmap
  accuracy: PCK
transforms:
  resizing:
    spatial_size: [512, 160]
    interpolation: bilinear
  padding:
    padding_ratio: [0.1, 0.1]
model:
  unet:
    spatial_dims: 2
    in_channels: 1
    out_channels: 68
    channels: [32, 64, 128, 256]
    strides: [2, 2, 2]
    kernel_size: 3
  hrnet:
    spatial_dims: 2
    in_channels: 1
    out_channels: 68
    channels: [32, 64, 128, 256]
    n_blocks: 4
    kernel_size: 3
    dropout: 0
  unet_base:
    in_channels: 1
    out_channels: 68
